---
title: "p8105_hw2_LDL2113"
author: "Lisa Eisler"
date: "9/30/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Problem 1

*Read and clean the Mr. Trash Wheel sheet:*

```{r}
mr_trash_wheel = 
  readxl::read_excel("./healthy_harbor.xlsx", sheet = 1, range = "A2:N338") %>%
  janitor::clean_names() %>%
  mutate(
    sports_balls = as.integer(sports_balls)) %>%
  drop_na()
```

*Read and clean precipitation data for 2017 and 2018*

```{r}
precipitation_2017 = 
  readxl::read_excel("./healthy_harbor.xlsx", sheet = 6, range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    year = 2017) %>%
  drop_na()

precipitation_2018 = 
  readxl::read_excel("./healthy_harbor.xlsx", sheet = 5, range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    year = 2018) %>%
  drop_na()

precipitation_2017_2018 = 
  bind_rows(precipitation_2017, precipitation_2018) %>%
  mutate(
    "month" = month.name[as.integer(month)])
```

For each, omit rows without precipitation data and add a variable year. Next, combine precipitation datasets and convert month to a character variable (the variable month.name is built into R and should be useful).